= mpca

mpca is a Groff macro package that conservatively extends the ms
package.  Its features include:

- blank lines as paragraph separators
- indexing
- table of contents
- code display
- image insertion (.svg, .jpeg, etc.)
- page references both backward and forward
- eval, i.e., extending groff using JavaScript or Common Lisp

Place the `pca*.tmac` files in your home directory or somewhere in
your `GROFF_TMAC_PATH`. mpca may be loaded into your groff source
as

  .mso pca

or invoked as a groff command-line option:

  groff -mpca ...

If using the indexing, table-of-contents, or eval features, you have to
use the `-U` groff command-line option for the first run, as groff
needs to be in “unsafe” mode so that mpca can create the external
auxiliary files needed.

You can use just the indexing or ToC or eval facilities in `pca.tmac`
without committing to the rest of it; see
link:pca-ix.adoc[], link:pca-toc.adoc[], and link:pca-eval.adoc[]
respectively.

mpca stands for “Macros for the Prevention of Cruelty to
Authors”.
